export interface Quote {
    text: string;
    author?: string;
}

export class QuoteService {
    private static quotes: Quote[] = [
        { text: "Sumir elska malbik, allir elska utanvega" },
        { text: "Pain is inevitable, suffering is optional" },
        { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
        { text: "Man is disturbed not by things, but by the view which he takes of them.", author: "Epictetus" },
        { text: "Pain is neither unbearable nor unending as long as you keep in mind its limits and don’t magnify them in your imagination.", author: "Marcus Aurelius" },
        { text: "90% of suffering is the story you tell yourself about what happened.", author: "Maxime Lagacé" },
        { text: "Pain is what the world does to you; suffering is what you do to yourself.", author: "Often attributed to the Buddha" },
        { text: "Pain * Resistance = Suffering.", author: "Shinzen Young" },
        { text: "What you resist, persists.", author: "Often attributed to Carl Jung" },
        { text: "The root of all suffering is attachment.", author: "Gautama Buddha" },
        { text: "Suffering is your perceptions clashing with reality.", author: "Unknown" },
        { text: "You can be cold, wet, and miserable, or you can just be cold and wet.", author: "Modern Proverb" },
        { text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
        { text: "Suffering ceases to be suffering at the moment it finds a meaning.", author: "Viktor Frankl" },
        { text: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", author: "Kahlil Gibran" },
        { text: "Be patient and tough; someday this pain will be useful to you.", author: "Ovid" },
        { text: "Of all the paths you take in life, make sure a few of them are dirt.", author: "John Muir" },
        { text: "And into the forest I go, to lose my mind and find my soul.", author: "Often attributed to John Muir" },
        { text: "Trail running is the antidote to a world addicted to speed.", author: "Christopher McDougall, author of Born to Run" },
        { text: "Go fast enough to get there, but slow enough to see.", author: "Unknown" },
        { text: "The danger of an adventure is worth a thousand days of ease and comfort.", author: "Paulo Coelho" },
        { text: "Run when you can, walk if you have to, crawl if you must; just never give up.", author: "Dean Karnazes" },
        { text: "It’s just a hill. Get over it.", author: "Common trail runner mantra" },
        { text: "When everything feels like an uphill struggle, just think of the view from the top.", author: "Unknown" },
        { text: "Forward is a pace.", author: "Common ultrarunning mantra" },
        { text: "The trail is a journey into yourself.", author: "Vanessa Rodriguez" },
        { text: "In long-distance running the only opponent you have to beat is yourself, the way you used to be." },
        { text: "I’m not a human. I’m a piece of machinery. I don’t need to feel a thing. Just forge on ahead.", author: "Haruki Murakami (mantra during a 62-mile ultramarathon)" },
        { text: "Exerting yourself to the fullest within your individual limits: that’s the essence of running.", author: "Haruki Murakami" },
        { text: "To appreciate the beauty of a snowflake, it is necessary to stand out in the cold.", author: "Aristotle" },
        { text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsch" },
        { text: "The miracle isn't that I finished. The miracle is that I had the courage to start.", author: "John Bingham" },
        { text: "There is no such thing as bad weather, only inappropriate clothing.", author: "Alfred Wainwright" },
        { text: "If you will never try, you will never know, your worth", author: "Coldplay" },
        { text: "The focus must be on learning from failure, not that you are a failure", author: "Lanny Bassham" },
        { text: "If you are not having loads of problems, your goals are to low", author: "Lanny Bassham" },
        { text: "Nothing can prepare you fpr the unknown, you just have to go for it.", author: "Hillary Allen" },
        { text: "Ofmetnastu ekki af lífsins móðurmjólk, kirkjugarðar heimsins geyma ómissandi fólk", author: "Magnús Eiríksson" },
        { text: "The greatest thing you'll ever learn Is just to love and be loved in return", author: "Nature boy" },
        { text: "Með ykkur mér við hlið, er ferðalagið létt", author: "Botnleðja" },
        { text: "Með ofbirtu í augunum, við þrömmum okkar leið. Ferðin verður löng, en gatan virðist greið.", author: "Botnleðja" },
        { text: "Þó ferðin virðist löng, hálfnað verk þá hafið er.", author: "Botnleðja" },
        { text: "You're on your own now, We won't save you, Your rescue squad is too exhausted...", author: "Björk" },
        { text: "Þú ferð þína eigin, ótroðnu slóð.", author: "KK, Vegbúinn" },
        { text: "Þetta er jörðin sem ég ann, þetta er landið sem ég ann.", author: "Magnús Sigmunds, Jörðin sem ég ann" },
        { text: "Get busy living, or get busy dying.", author: "Andy Dufresne, Shawshank Redemption." },
        { text: "Oooh, what a lucky man.", author: "Emerson, Lake & Palmer" },
        { text: "Ain't no mountain high enough.", author: "Ashford & Simpson" },
        { text: "Tek að mér verkefni og kláraða.", author: "Emmsé Gauti" },
        { text: "Þar sem er vilji, þar er vegur." },
        { text: "The first one now, will later be last.", author: "Bob Dylan" },
        { text: "The present now will later be past", author: "Bob Dylan" },
        { text: "It's another day for you and me in paradise.", author: "Phil Colling" },
        { text: "Ekkert mál", author: "Grýlurnar :)" },
        { text: "Sterkur og stór til fjalla fó,r" },
        { text: "Skjótur varstu vinur og vaskur í för." },
        { text: "Hello from the other side", author: "Adele" },
        { text: "Where you stumble, there lies your treasure.", author: "Joseph Campbell" },
        { text: "Nothing worth doing, is easy", author: "Roosevelt" },
        { text: "If you want to go fast, go alone. If you want to go far, go together", author: "African proverb" },
        { text: "Draumarnir eru stöffið sem við nærumst öll á", author: "Bubbi Morthens" },
        { text: "Big old mountain looking at me; says I'm the lucky one", author: "KK" },
        { text: "Ég kýs, ástina og lífið", author: "Jóhann Helgason" },
        { text: "Don't stop me now, I'm having such a good time" },
        { text: "Light up your face with gladness, if you just smile", author: "Charlie Chaplin" },
        { text: "Nobody said it was easy", author: "Coldplay" },
        { text: "We're so happy and that's how we're gonna stay", author: "Manfred Mann" }
    ];

    static getRandomQuote(): Quote {
        const randomIndex = Math.floor(Math.random() * this.quotes.length);
        return this.quotes[randomIndex];
    }
}
